version: 2

sources:
  - name: decoded_contracts
    description: "Decoded Contracts"
    schema: decoded_contracts
    tables:
      - name: dune_abis
      - name: decode_contracts
      - name: spellbook_dependent_names

  - name: decoded_projects
    description: "Decoded Projects"
    schema: decoded_projects
    tables:
      - name: dune_abis
      - name: abi_to_ordinal_dune
      - name: address_to_ordinal_dune  

  - name: ethereum
    schema: ethereum
    tables:
      - name: transactions
      - name: logs_clustered
      - name: one_day_logs
      - name: logs
      - name: traces_clustered
      - name: one_day_traces
      - name: traces
      - name: blocks
      - name: contracts
      - name: token_types

  - name: goog_mainnet_ethereum
    database: bigquery-public-data
    schema: goog_blockchain_ethereum_mainnet_us
    description: "Ethereum logs from new Crypto Dataset"
    tables:
      - name: transactions
      - name: logs
      - name: traces
      - name: blocks
      - name: contracts

  - name: crypto_ethereum
    database: bigquery-public-data
    schema: crypto_ethereum
    description: "Ethereum logs from new Crypto Dataset"
    tables:
      - name: transactions
      - name: logs
      - name: traces
      - name: blocks
      - name: contracts